<?php
/**
 * Created by PhpStorm.
 * User: punker
 * Date: 9/1/14
 * Time: 9:50 PM
 */

namespace MikeWu\Schedule\Tests;


use MikeWu\Schedule\CsvParser;

class CsvParserTest extends \PHPUnit_Framework_TestCase {

    public function testParseSchedule()
    {
        $schedule = ["","EL, BROWN, 100, JOE", "EL, BLUE, 120, PETE", "Metra, West, 312ZZ, TOM", "Amtrak, NORTH, 123N, Mike", "EL, NORTH, 123N, Mike", "EL, NORTH, 123N, Mike", "EL, NORTH, 123N, Tom"];
        $this->assertEquals("EL",$this->CsvParser->parseSchedule($schedule)["100"]->getTrain_line());
        $this->assertEquals("EL",$this->CsvParser->parseSchedule($schedule)["120"]->getTrain_line());
        $this->assertEquals("Metra",$this->CsvParser->parseSchedule($schedule)["312ZZ"]->getTrain_line());
        $this->assertEquals("Amtrak",$this->CsvParser->parseSchedule($schedule)["123N"]->getTrain_line());
        $this->assertEquals("Mike",$this->CsvParser->parseSchedule($schedule)["123N"]->getOperator_id());
        $this->assertEquals("BLUE",$this->CsvParser->parseSchedule($schedule)["120"]->getRoute_name());
        $this->assertEquals(6,count($this->CsvParser->parseSchedule($schedule)));

    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->CsvParser = new CsvParser();
    }

    protected function tearDown()
    {
        $this->CsvParser = null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }





}
 