<?php
/**
 * Created by PhpStorm.
 * User: punker
 * Date: 9/1/14
 * Time: 9:19 PM
 */

namespace MikeWu\Schedule\Tests;


use MikeWu\Schedule\ElSchedule;
use MikeWu\Schedule\MetraSchedule;

class ElScheduleTest extends \PHPUnit_Framework_TestCase {


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->ElSchedule = new ElSchedule();
    }

    protected function tearDown()
    {
        $this->ElSchedule = null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test__construct()
    {
        $this->ElSchedule->__construct();
        $this->assertEquals("EL", $this->ElSchedule->getTrain_line());
    }

    public function testEquals() {
        $other = new ElSchedule();
        $other->setOperator_id("OID");
        $other->setRoute_name("RN");
        $other->setRun_number("RNU");

        $this->ElSchedule->setOperator_id("OID");
        $this->ElSchedule->setRoute_name("RN");
        $this->ElSchedule->setRun_number("RNU");

        $this->assertTrue($this->ElSchedule->equals($other));

        $other->setRoute_name("ORN");
        $this->assertFalse($this->ElSchedule->equals($other));

        $other = new MetraSchedule();
        $other->setOperator_id("OID");
        $other->setRoute_name("RN");
        $other->setRun_number("RNU");

        $this->assertFalse($this->ElSchedule->equals($other));
    }


}
 